### ISSUE TITLE
The AUC is so low in the evaluation for stage two

### ISSUE THREAD

**Issue by multimedia-infomation-security** [DTaoo/Discriminative-Sounding-Objects-Localization#14]
I run training_stage_two.py with  5 epochs   learning_rate 1e-4  batch_size 32,   the train acc is nearly 0.875 and eva acc is nearly 0.8 
then I run :
_match_cluster.py_
_test_stage_two.py_(use the pretrained weight aquired in training_stage_two.py)
after this,I run _eval.py_, but the AUC is quite lower than you, which is about 0.05, and the visualize result is very inaccurate. I have trained so many times but the AUC is always so low,I cannot find out the reason, I am so sorry to bother you ,but can you give me some advice for this ?

I will appreciate it if you can contact me in my wechat(L18355043548) or my mailbox(2869612559@qq.com)

**Comment by IFICL** [comment]
Sorry to bother you. Did you fix this problem? In my part, AUC and cIOU are quite close. I wonder the AUC has the right definition.

**Comment by DTaoo** [comment]
Have contacted you, thx
