### ISSUE TITLE
Bounding Box Annotation for MUSIC dataset

### ISSUE THREAD

**Issue by krantiparida** [DTaoo/Discriminative-Sounding-Objects-Localization#8]
As mentioned in the paper, Faster RCNN was used for detecting 15 instruments as per AudioSet-instrument dataset but MUSIC dataset contains some other instruments that are not available in MUSIC. How are the extra objects annotated?

**Comment by DTaoo** [comment]
> As mentioned in the paper, Faster RCNN was used for detecting 15 instruments as per AudioSet-instrument dataset but MUSIC dataset contains some other instruments that are not available in MUSIC. How are the extra objects annotated?

We did not annotate the object if its category is not in the AudioSet-instrument dataset, hence we exclude this part in the test phase.

**Comment by krantiparida** [comment]
Thanks for the clarification.
